### ISSUE TITLE
This is not allowed since there's already a kernel registered from python overriding unpack's behavior for CPU dispatch key and quanto_ext namespace.

### ISSUE THREAD

**Issue by arseniybelkov** [huggingface/optimum-quanto#285]
I am trying to run this code
```python
from optimum.quanto import quantize, freeze, qint8
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.layers = nn.Sequential(*[nn.Linear(16, 16) for _ in range(3)])

    def forward(self, x):
        return self.layers(x)

model = Model()
model.to("cuda")
model.eval()
```
it results in the error
```
Traceback (most recent call last):
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/transformers/generation/configuration_utils.py", line 48, in <module>
    from ..cache_utils import QuantizedCacheConfig
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/transformers/cache_utils.py", line 18, in <module>
    from quanto import AffineQuantizer, MaxOptimizer, qint2, qint4
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/quanto/__init__.py", line 18, in <module>
    from .library import *
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/quanto/library/__init__.py", line 15, in <module>
    from .ext import *
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/quanto/library/ext/__init__.py", line 17, in <module>
    from .cpp import *
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/quanto/library/ext/cpp/__init__.py", line 49, in <module>
    @torch.library.impl("quanto_ext::unpack", ["CPU"])
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/torch/library.py", line 442, in register
    use_lib.impl(qualname, func, key)
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/torch/library.py", line 234, in impl
    raise RuntimeError("This is not allowed since there's already a kernel registered from python overriding {}"
RuntimeError: This is not allowed since there's already a kernel registered from python overriding unpack's behavior for CPU dispatch key and quanto_ext namespace.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1603, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/transformers/modeling_utils.py", line 46, in <module>
    from .generation import GenerationConfig, GenerationMixin
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.configuration_utils because of the following error (look up to see its traceback):
This is not allowed since there's already a kernel registered from python overriding unpack's behavior for CPU dispatch key and quanto_ext namespace.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/belkov.arseniy/paligemma/run_predictions.py", line 154, in <module>
    from optimum.quanto import quantize, freeze, qint8
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/optimum/quanto/__init__.py", line 19, in <module>
    from .models import *
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/optimum/quanto/models/__init__.py", line 30, in <module>
    from .transformers_models import *
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/optimum/quanto/models/transformers_models.py", line 30, in <module>
    from transformers import AutoConfig, AutoModelForCausalLM, PreTrainedModel
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1593, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/belkov.arseniy/miniconda3/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1605, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_utils because of the following error (look up to see its traceback):
Failed to import transformers.generation.configuration_utils because of the following error (look up to see its traceback):
This is not allowed since there's already a kernel registered from python overriding unpack's behavior for CPU dispatch key and quanto_ext namespace.
```

**Comment by bghira** [comment]
can't reproduce it on MacOS via MPS but i can on nvidia

**Comment by ejektaflex** [comment]
Same here, same unpack behaviour error on Nvidia/Linux.

**Comment by bghira** [comment]
pip uninstall quanto
but keep optimum-quanto

maybe maintainer can remove quanto package from pypi

**Comment by arseniybelkov** [comment]
@bghira thanks, it helped
