### ISSUE TITLE
issues with non-contiguous Tensor

### ISSUE THREAD

**Issue by bghira** [huggingface/optimum-quanto#327]
hello @dacorvo thanks for all the prompt feedback so far.

I might be doing something suboptimally or just incorrectly, but we're running into this a lot where `.view()` is being used on non-contiguous tensors. this happens with SDXL and Flux training, whether or not we are using LyCORIS, PEFT, or just directly tuning a quantised model.

this sort of workaround is applied:

```py
if input.is_contiguous():
    reshaped_input = input.view(-1, in_features)
else:
    reshaped_input = input.reshape(-1, in_features)
output = torch._weight_int4pack_mm(
    reshaped_input.to(dtype=other.dtype),
    other._data._data,
    other._group_size,
    other._scale_shift,
)
```
which avoids unnecessary copy overhead.

However, my list of workarounds is growing forever-larger.

Is this something that can be addressed on my side, or is it something that is missing in Quanto itself?

**Comment by dacorvo** [comment]
Hi @bghira we should always use reshape instead of view. I will make the changes.

**Comment by Thomas2419** [comment]
Hello I thought I'd add this here since you're saying we should be using reshape anyway: 
"Traceback (most recent call last):
  File "/home/thomas/Desktop/bert_classifier/train_new.py", line 167, in <module>
    trainer.train()
  File "/home/thomas/anaconda3/lib/python3.12/site-packages/transformers/trainer.py", line 2241, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/anaconda3/lib/python3.12/site-packages/transformers/trainer.py", line 2548, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/anaconda3/lib/python3.12/site-packages/transformers/trainer.py", line 3740, in training_step
    self.accelerator.backward(loss, **kwargs)
  File "/home/thomas/anaconda3/lib/python3.12/site-packages/accelerate/accelerator.py", line 2454, in backward
    loss.backward(**kwargs)
  File "/home/thomas/anaconda3/lib/python3.12/site-packages/torch/_tensor.py", line 626, in backward
    torch.autograd.backward(
  File "/home/thomas/anaconda3/lib/python3.12/site-packages/torch/autograd/__init__.py", line 347, in backward
    _engine_run_backward(
  File "/home/thomas/anaconda3/lib/python3.12/site-packages/torch/autograd/graph.py", line 823, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/anaconda3/lib/python3.12/site-packages/torch/autograd/function.py", line 307, in apply
    return user_fn(self, *args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/thomas/anaconda3/lib/python3.12/site-packages/optimum/quanto/tensor/function.py", line 58, in backward
    other_gO = torch.matmul(gO.view(-1, out_features).t(), input.view(-1, in_features))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead."

**Comment by ishanExtreme** [comment]
Hi @Thomas2419 I faced the same issue while quantizing whisper model.

I fixed it by replacing .view in function.py with .reshape and create a PR for the same. Maybe it can solve your issue as well

https://github.com/huggingface/optimum-quanto/pull/412
