### ISSUE TITLE
"does not have a parameter or a buffer named input_scale" in quanto FluxTransformer2DModel

### ISSUE THREAD

**Issue by LianShuaiLong** [huggingface/optimum-quanto#359]
@sayakpaul
here is my quanto code:
 
   from optimum.quanto.models import QuantizedDiffusersModel
   class QuantizedFluxTransformer2DModel(QuantizedDiffusersModel):
        base_class = FluxTransformer2DModel
   model = FluxTransformer2DModel.from_pretrained("./FLUX.1-schnell",subfolder="transformer")
   qmodel = QuantizedFluxTransformer2DModel.quantize(model,weights=qfloat8)
   qmodel.save_pretrained("./FLUX.1-schnell-fp8")

no errors in quanto process
but valueError raise when infer with the quanto model:
ValueError: Linear(in_features=4096, out_features=3072, bias=True) does not have a parameter or a buffer named input_scale
here is my inference code:

   pipeline = FluxPipeline.from_pretrained(
            "./FLUX.1-schnell",
            transformer=None,
            torch_dtype=torch.float16
            ).to("cuda")
    transformer = FluxTransformer2DModel.from_pretrained("./FLUX.1-schnell-fp8")
    transformer.to("cuda",dtype=torch.float16)
    pipeline.transformer = transformer
    prompt = "a cat"
    image = pipeline(
            prompt=prompt,
            num_inference_steps=4,
            num_images_per_prompt=1,
            width=512,
            height=512,
            generator = torch.Generator.manual_seed(42)
        ).images[0]
    image.save('cat.png')

**Comment by Deng-Xian-Sheng** [comment]
me too

this is my code

```python
model_id = 'black-forest-labs/FLUX.1-dev'
adapter_id = '/root/autodl-tmp/checkout-redbook/checkpoint-3500'

from diffusers import DiffusionPipeline
import torch

pipeline = DiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.bfloat16)
pipeline.load_lora_weights(adapter_id, adapter_name="china-girl")
pipeline.set_adapters(["china-girl"], adapter_weights=[0.8])

pipeline.fuse_lora(adapter_names=["china-girl"], lora_scale=1.0)

pipeline.unload_lora_weights()

from optimum.quanto import quantize, freeze, qint8
quantize(pipeline.transformer, weights=qint8)
freeze(pipeline.transformer)

# save locally
pipeline.save_pretrained("/root/autodl-tmp/checkout-redbook/flux-dev-china-girl-lora-merge")
```

And load code
```python
# 配置模型参数 --------------------------------------------------------
model_id = "/root/autodl-tmp/checkout-redbook/flux-dev-china-girl-lora-merge"
output_test_dir = "/root/autodl-tmp/xxx-test"

# 负向提示词（描述不希望出现的图像特征）
negative = "deep fried watermark cropped out-of-frame low quality low res oorly drawn bad anatomy wrong anatomy extra limb missing limb floating limbs (mutated hands and fingers)1.4 disconnected limbs mutation mutated ugly disgusting blurry amputation synthetic rendering"
            
import torch
from diffusers import DiffusionPipeline
import time

pipeline = DiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.bfloat16).to("cuda") # loading directly in bf16

# 生成测试图像 ----------------------------------------------------
while True:
    # 从命令行接收用户输入的prompt
    prompt = input("\n请输入提示词 (输入 'exit' 退出): ").strip()
            
    if prompt.lower() == 'exit':
        print("接收到退出指令，结束生成。")
        break
    if not prompt:
        print("提示词不能为空，请重新输入。")
        continue

    current_time = time.time()
    print(f"Generating {output_test_dir}/{current_time}.png")
    print(f"Prompt: {prompt}")
    print(f"Negative: {negative}")

    try:
        image = pipeline(
            prompt=prompt,
            negative_prompt=negative,
            num_inference_steps=20,
            generator=torch.manual_seed(42),
            width=1024,
            height=1024,
            guidance_scale=3.0,
        ).images[0]
        image.save(f"{output_test_dir}/{current_time}.png", format="PNG")
        
    except Exception as e:
        print(f"生成过程中发生错误: {e}", exc_info=True)
        continue

print("程序退出。")
```

But load error

this is log
```
(.venv) root@autodl-container-0c7944b0f2-ea9fa930:~/autodl-tmp/SimpleTuner# PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" HF_HOME=/root/autodl-tmp/model python inference.py 
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  7.31it/s]
Loading pipeline components...:  71%|██████████████████████████████████████████████████████████████████████████▎                             | 5/7 [00:00<00:00, 10.56it/s]You set `add_prefix_space`. The tokenizer needs to be converted from the slow tokenizers
Loading pipeline components...: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  5.11it/s]
[2025-03-19 06:14:25,031] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
(.venv) root@autodl-container-0c7944b0f2-ea9fa930:~/autodl-tmp/SimpleTuner# PYTORCH_CUDA_ALLOC_CONF="expandable_segments:True" HF_HOME=/root/autodl-tmp/model python inference2.py 
Loading pipeline components...:  43%|████████████████████████████████████████████▌                                                           | 3/7 [00:00<00:00,  5.93it/s]
Traceback (most recent call last):
  File "/root/autodl-tmp/SimpleTuner/inference2.py", line 12, in <module>
    pipeline = DiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.bfloat16).to("cuda") # loading directly in bf16
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 924, in from_pretrained
    loaded_sub_model = load_sub_model(
                       ^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/pipelines/pipeline_loading_utils.py", line 725, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SimpleTuner/.venv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/SimpleTuner/.venv/lib/python3.11/site-packages/diffusers/models/modeling_utils.py", line 932, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
  File "/root/autodl-tmp/SimpleTuner/.venv/lib/python3.11/site-packages/accelerate/big_modeling.py", line 615, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/root/autodl-tmp/SimpleTuner/.venv/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 1945, in load_checkpoint_in_model
    set_module_tensor_to_device(
  File "/root/autodl-tmp/SimpleTuner/.venv/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 255, in set_module_tensor_to_device
    raise ValueError(f"{module} does not have a parameter or a buffer named {tensor_name}.")
ValueError: Linear(in_features=3072, out_features=3072, bias=True) does not have a parameter or a buffer named input_scale.
```
